language: python
python:
  - "2.7"
install:
  - pip install -r requirements/dev.txt
  - pip install coveralls==1.1
before_script:
  - flake8 assets_server --exclude dev_settings.py
script:
  - py.test
after_success:
  - coveralls
