---

defaults: &defaults
  docker:
    - image: canonicalwebteam/dev
  working_directory: /srv

version: 2
jobs:
  lint-python:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Lint python code
          command: yarn lint-python
  test-python:
    <<: *defaults
    environment:
      - DB_URL: sqlite://
    steps:
      - checkout
      - run:
          name: Yarn install
          command: yarn install
      - run:
          name: Yarn build
          command: yarn build
      - run:
          name: Install requirements
          command: pip3 install -r requirements.txt
      - run:
          name: Install dependencies
          command: pip3 install coverage
      - run:
          name: Run tests with coverage
          command: |
            coverage run  --source=. -m unittest discover tests
            bash <(curl -s https://codecov.io/bash) -cF python
  test-site:
    <<: *defaults
    environment:
      - DB_URL: sqlite://
    steps:
      - checkout
      - run:
          name: Install yarn dependencies
          command: yarn
      - run:
          name: Install pip dependencies
          command: pip3 install -r requirements.txt
      - run:
          name: Run the site server
          command: ./entrypoint 0.0.0.0:80
          background: true
      - run:
          name: Check site is accessible
          command: sleep 1 && curl --head --fail --retry-delay 5 --retry 10  --retry-connrefused http://localhost/_status/check
workflows:
  version: 2
  build:
    jobs:
      - lint-python
      - test-python
      - test-site
