---

defaults: &defaults
  docker:
    - image: canonicalwebteam/dev
  working_directory: /srv

version: 2
jobs:
  test-site:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install yarn dependencies
          command: yarn
      - run:
          name: Install pip dependencies
          command: pip3 install -r requirements.txt && pip install gunicorn
      - run:
          name: Install mongo
          command: apt-get install -y mongodb
      - run:
          name: Run the site server
          command: gunicorn webapp.wsgi -b 0.0.0.0:80
          background: true
      - run:
          name: Check site is accessible
          command: sleep 1 && curl --head --fail --retry-delay 5 --retry 10  --retry-connrefused http://localhost
  lint-python:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip3 install flake8 black
      - run:
          name: Lint webapp with flake8 & Black
          command: flake8 webapp/ integration_tests/ && black --check --line-length 79 webapp/ integration_tests/
workflows:
  version: 2
  build:
    jobs:
      - test-site
      - lint-python
